apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rs
  template:
    metadata:
        labels:
          app: rs
    spec:
      containers:
        - name: rs
          image: ahmedyousseff/gaza-be:v17
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rs
  template:
    metadata:
      labels:
        app: rs
    spec:
      containers:
        - name: rs
          image: ahmedyousseff/gaza-be:v1
          imagePullPolicy: IfNotPresent